import pyautogui
import time

pyautogui.press('winleft')
time.sleep(1)
pyautogui.write('chrome')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.moveTo(1042, 455, 1)
time.sleep(1.5)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(188, 63)
time.sleep(1)
pyautogui.click()
time.sleep(1)
pyautogui.write('https://www.youtube.com/')
time.sleep(1)
pyautogui.press('enter')
time.sleep(5)
pyautogui.moveTo(702,116)
time.sleep(1)
pyautogui.click()
pyautogui.write('Caze TV')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1.5)
pyautogui.moveTo(1639,911)
time.sleep(1)
pyautogui.click()
time.sleep(1)
pyautogui.alert(title='agradecimento', text='Obrigado por se inscrever no canal', button='Ok')